name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Backend build & push
      - name: Build backend image
        run: docker build -t aiyus/simple-ecommerce-backend ./api

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push backend image
        run: docker push aiyus/simple-ecommerce-backend

      # Frontend build & push
      - name: Build frontend image
        run: docker build -t aiyus/simple-ecommerce-frontend ./webapp

      - name: Push frontend image
        run: docker push aiyus/simple-ecommerce-frontend

      # Deploy to EC2
      - name: SSH Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull aiyus/simple-ecommerce-backend
            docker stop backend-container || true
            docker rm backend-container || true
            docker run -d --name backend-container -p 5000:5000 aiyus/simple-ecommerce-backend

            docker pull aiyus/simple-ecommerce-frontend
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d --name frontend-container -p 80:80 aiyus/simple-ecommerce-frontend
            echo "Deployment to EC2 completed successfully!"